RECEIPT_DATA_DIR = "./tests/data/receipt"
INVOICE_DATA_DIR = "./tests/data/invoice"
US_BANK_CHECK_DATA_DIR = "./tests/data/us/bank_check"
PASSPORT_DATA_DIR = "./tests/data/passport"
FR_CARTE_GRISE_DATA_DIR = "./tests/data/fr/carte_grise"
CUSTOM_DATA_DIR = "./tests/data/custom"
CROPPER_DATA_DIR = "./tests/data/cropper"
PDF_DATA_DIR = "./tests/data/pdf"
