name: Crontab

on:
  schedule:
  - cron: '32 0 * * *'

permissions:
  contents: read
  packages: read
  actions: read

jobs:
  test-regressions:
    uses: mindee/mindee-api-python/.github/workflows/_test-regressions.yml@main
    secrets: inherit
  test-code-samples:
    uses: mindee/mindee-api-python/.github/workflows/_smoke-test.yml@main
    secrets: inherit
  test-cli:
    uses: mindee/mindee-api-python/.github/workflows/_test-cli.yml@main
    secrets: inherit
