name: Crontab

on:
  schedule:
  - cron: '32 0 * * *'

jobs:
  test-regressions:
    uses: mindee/mindee-api-python/.github/workflows/_test-regressions.yml@main
    secrets: inherit
  test-code-samples:
    uses: mindee/mindee-api-python/.github/workflows/_test-code-samples.yml@main
    secrets: inherit
