#
# Publish Documentation to GitHub pages.
#
name: Publish Documentation

on:
  release:
    types: [ published ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  documentation:
    name: Publish Documentation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-docs-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-docs-

    - name: Install dependencies
      run: |
        python -m pip install -e .[docs]

    - name: Sphinx make
      run: |
        cd ./docs
        make html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
