name: Pull Request

on:
  pull_request:

jobs:
  static-analysis:
    uses: mindee/mindee-api-python/.github/workflows/_static-analysis.yml@main
  test-units:
    uses: mindee/mindee-api-python/.github/workflows/_test-units.yml@main
    needs: static-analysis
    secrets: inherit
  test-regressions:
    uses: mindee/mindee-api-python/.github/workflows/_test-regressions.yml@main
    needs: test-units
    secrets: inherit
  test-integrations:
    uses: mindee/mindee-api-python/.github/workflows/_test-integrations.yml@client-v2
    needs: test-units
    secrets: inherit
  test-code-samples:
    uses: mindee/mindee-api-python/.github/workflows/_test-code-samples.yml@client-v2
    needs: test-units
    secrets: inherit
