name: Pull Request

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  static-analysis:
    uses: ./.github/workflows/_static-analysis.yml
  test-units:
    uses: ./.github/workflows/_test-units.yml
    needs: static-analysis
    secrets: inherit
  test-regressions:
    uses: ./.github/workflows/_test-regressions.yml
    needs: test-units
    secrets: inherit
  test-integrations:
    uses: ./.github/workflows/_test-integrations.yml
    needs: test-units
    secrets: inherit
  test-code-samples:
    uses: ./.github/workflows/_test-code-samples.yml
    needs: test-units
    secrets: inherit
