name: Push Main Branch

on:
  push:
    branches:
      - main

jobs:
  static_analysis:
    uses: mindee/mindee-api-python/.github/workflows/_static-analysis.yml@main
  test_units:
    uses: mindee/mindee-api-python/.github/workflows/_test-units.yml@main
    needs: static_analysis
    secrets: inherit
  tag:
    uses: mindee/client-lib-actions/.github/workflows/tag-version.yml@main
    needs: test_units
